### ISSUE TITLE
对report1的意见

### ISSUE THREAD

**Issue by jiexray** [nksoftware/restaurant_automation#1]
# 大家下载report1，看过之后发表一下自己的想法，田霖要继续完善。

**Comment by jiexray** [comment]
## 关于report1:
1. 我认为我们不应该让客户输入他们的名字，这是个人隐私问题。
   我们应该给每一个到店客户一个就餐号，客户可以自行将就餐号与自己的账户进行绑定（手机）。
   之后客户就可以通过这个就餐号获得他需要的服务和信息。
2. 没有桌子可用的时候，我们首先要将客户进行排队，并告知客户所需要等待的桌数（前面有多少个等待客户）

### 整体结构不错，重点有所突出（选座、点餐）。也有一部分的扩展功能，简略地进行描述。

就是我们web的工作计划，你帮我们扩写点，我们写的比较概括，你可以就一个功能的特点，写一点东西，不用写具体的界面、逻辑流程。
例如：点餐：服务器为服务员和客户提供点餐的后台逻辑支持，实现从菜品展示、菜品选择\修改、菜品确认下单的一系列操作流程，并通过与app端的界面对接，使得这些功能能够真正展现在用户的面前，以简洁、高效的操作流程，完成点餐的功能。

## 有什么不清楚的可以问哦。

**Comment by TianlinZhang668** [comment]
快考虑剩下的吧，还有好多呢

来自 魅族 MX4

-------- 原始邮件 --------
发件人：xia rui notifications@github.com
时间：周日 3月20日 16:01
收件人：nksoftware/restaurant_automation restaurant_automation@noreply.github.com
主题：Re: [restaurant_automation] 对report1的意见 (#1)
